### ISSUE TITLE
Add BEL_MILLIWATT in UCUM units

### ISSUE THREAD

**Issue by maximelefrancois86** [unitsofmeasurement/uom-systems#120] opened 2018-03-22 08:49 UTC
Dear all, 

I know UCUM doesn't defined B(mW), but that unit is quite important to qualify antennas, could it be added here ?

That would be adding in `ucum-java8/src/main/java/systems/uom/ucum/UCUM.java`

```
     @SuppressWarnings("unchecked")
     public static final Unit<Level<Power>> BEL_MILLIWATT = addUnit(
 	    MILLI(WATT).transform(new LogConverter(10)).asType(Level.class));
```

Best
Max

**Comment by keilw** [comment] 2018-03-22 12:20
Thanks, but I'm afraid, we cannot progress with this and https://github.com/unitsofmeasurement/uom-systems/pull/119 unless the UCUM group accepted a proposal for addition, see http://unitsofmeasure.org/trac/wiki/RequestsForUnit. I can tell you from my own experience (I proposed a unit very common in the textile industry in 2010 and it took roughly 5 years, till they added it) this can be tedious and UCUM is a very small group of people (1 or 2) who decide what to add and when. The **Unicode CLDR** and **UCUM** systems here must not exceed the actual standards. they can under certain circumstances decide to define fewer units (e.g. the prefixes like KILO or MILLI, Unicode has its own units while we offer a combination of prefixes) but they must not invent something that would be incompatible with the underlying standards. 

We recently added a "Cloud" module to https://github.com/unitsofmeasurement/uom-domain for performance monitoring and support of MicroProfile Metrics.

Would you like to propose something under uom-domain?
uom-demos have https://github.com/unitsofmeasurement/uom-demos/tree/master/domain/energy but so far there is no domain-specific library. If "energy" sounds well for WATT, I would suggest that name also for the domain-specific module, otherwise please advise what you think is a better name?

Because such units are likely of great benefit to Eclipse projects like SmartHome, would you mind signing the Eclipse Contributor agreement before or soon after contributiong to those modules?

Thanks,
Werner

**Comment by keilw** [comment] 2018-03-22 13:20
This could be related or even a duplicate of https://github.com/unitsofmeasurement/uom-systems/issues/59

**Comment by keilw** [comment] 2018-03-24 23:52
Closing because it is a duplicate/subset of https://github.com/unitsofmeasurement/uom-systems/issues/59

**Closed by keilw** 2018-03-24 23:52 UTC
Labels: duplicate, system:ucum
