### ISSUE TITLE
Version 1.0 is Broken for Formatting kg/m2

### ISSUE THREAD

**Issue by alexanderkiel** [unitsofmeasurement/uom-systems#139] opened 2019-05-07 09:49 UTC
I already commented at #135 but would like to emphasize the regression here again.

**Comment by keilw** [comment] 2019-05-07 10:49
Thanks but this is mostly a duplicate of #135 then. Version 1.0 has not included a fix for it, was mostly released to include SI Units 1.0 but due to an already fixed bug a 1.1 release is inevitable. We wanted to keep them in sync to avoid confusion. Both might see a few more minor changes towards World Metrology Day because BIPM and other organizations won't release their source documents before then.

**Closed by keilw** 2019-05-07 10:49 UTC
Labels: duplicate

**Comment by alexanderkiel** [comment] 2019-05-07 15:28
Sorry for the duplicate and thanks for your fast reaction.
